### ISSUE TITLE
luuk is gemeen

### ISSUE THREAD

**Issue by otherwise777** [Grabot/TimeReach#1]
vandaag maakte luuk sarcastische grapjes die ik niet snapte, hier ben ik niet van gediend

**Comment by LuukvH** [comment]
Beste meneer otherwise777,
Bedankt voor het inzenden van uw klacht met ticket nummer #32B3UL43LSH9IT
Wij zullen u klacht zo spoedig mogelijk in behandeling nemen.
Dit houdt in dat deze klacht netjes wordt opgeslagen in onze database wordt opgeslagen en vervolgens totaal genegeert.

Met vriendelijke groet,

Manager klachten afhandeling.
Luuk van Hulten

**Comment by whazor** [comment]
wegpesten!!

**Comment by giedomak** [comment]
Geachte @otherwise777 ,

Hierbij bevestigen wij de ontvangst van uw reactie betreffende de opmerkingen van @LuukvH . Team Data Bazen hecht veel waarde aan de mening van onze klanten en wij stellen uw reactie dan ook erg op prijs.

Wij vinden het spijtig dat de communicatie niet naar wens is verlopen, maar ons inziens hebben wij alles gedaan om de communicatie zo spoedig mogelijk te laten verlopen.

Wij hopen op uw begrip.

Om u toch enigszins tegemoet te komen willen wij u 30% korting aanbieden op uw volgende commit. Deze korting wordt automatisch verrekend wanneer u een nieuwe commit plaatst.

Met vriendelijke groet,
Team Data Bazen
